# Generated by Django 5.2.4 on 2025-07-15 14:32

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('support', 'Support'), ('driver', 'Driver'), ('customer', 'Customer')], default=users.models.Role['CUSTOMER'], max_length=50),
        ),
    ]
