# Generated by Django 5.2.4 on 2025-07-16 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 16, 15, 52, 22, 511723, tzinfo=datetime.timezone.utc)),
        ),
    ]
