# Generated by Django 5.2.4 on 2025-07-30 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_activation_code_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 30, 15, 24, 34, 183620, tzinfo=datetime.timezone.utc)),
        ),
    ]
