# Generated by Django 5.2.4 on 2025-07-30 15:26
from django.db import migrations
import uuid

def populate_activation_codes(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.all():
        user.activation_code = uuid.uuid4()
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_activation_code_alter_user_date_joined'),
    ]

    operations = [
        migrations.RunPython(populate_activation_codes),
    ]
