# Generated by Django 5.2.4 on 2025-07-30 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_date_joined'),
        ('users', '0015_populate_activation_codes'),
    ]

    operations = [
    ]
