# Generated by Django 5.2.4 on 2025-07-30 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_merge_20250730_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 30, 15, 38, 51, 604311, tzinfo=datetime.timezone.utc)),
        ),
    ]
