# Generated by Django 5.2.4 on 2025-07-30 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 30, 18, 38, 48, 640236, tzinfo=datetime.timezone.utc)),
        ),
    ]
