
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: myproject
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  mailpit:
    image: ghcr.io/axllent/mailpit:latest
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"


  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000 "
    volumes:
      - .:/myproject
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - mailpit

volumes:
  postgres_data:
