# Generated by Django 5.2.4 on 2025-07-16 18:32

import food.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=food.models.OrderStatus.choices, default=food.models.OrderStatus['NOT_STARTED'], max_length=50),
        ),
    ]
