# Generated by Django 5.2.5 on 2025-08-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(blank=True, default='pending', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_tracking_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
